import{a as b,S as v,i as a}from"./assets/vendor-DxEWe7lX.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const S="50359278-45963637c7b66305440920a80",q="https://pixabay.com/api/";async function m(o,e){const r={key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};return(await b.get(q,{params:r})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more"),P=new v(".gallery a");function p(o){const e=o.map(r=>`
    <li class="gallery__item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" class="img-search"/>
      </a>
      <div class="info">
        <p class="p-info-img"><b>Likes</b> ${r.likes}</p>
        <p class="p-info-img"><b>Views</b> ${r.views}</p>
        <p class="p-info-img"><b>Comments</b> ${r.comments}</p>
        <p class="p-info-img"><b>Downloads</b> ${r.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",e),P.refresh()}function B(){f.innerHTML=""}function y(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function $(){h.classList.remove("hidden")}function u(){h.classList.add("hidden")}let n="",i=1,w=0;const H=document.querySelector("#form-info"),d=document.querySelector(".load-more");H.addEventListener("submit",async o=>{if(o.preventDefault(),n=o.target.elements.searchQuery.value.trim(),!n){a.warning({message:"Please enter a search term!"});return}i=1,B(),u(),y(),await new Promise(e=>setTimeout(e,1e3));try{const e=await m(n,i);if(w=e.totalHits,e.hits.length===0){a.info({message:"No images found. Try another search."});return}p(e.hits),e.totalHits>15&&$(),e.totalHits<=15&&u()}catch{a.error({message:"An error occurred. Try again later."})}finally{L()}});d.addEventListener("click",async()=>{i+=1,d.classList.toggle("hidden"),y(),await new Promise(o=>setTimeout(o,1e3)),d.classList.toggle("hidden");try{const o=await m(n,i);p(o.hits),M(),document.querySelectorAll(".gallery-item").length>=w&&(u(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Failed to load more images."})}finally{L()}});function M(){const{height:o}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
