import{a as w,S as v,i as a}from"./assets/vendor-DxEWe7lX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="50359278-45963637c7b66305440920a80",q="https://pixabay.com/api/";async function m(r,t){const o={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await w.get(q,{params:o})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),B=new v(".gallery a");function y(r){const t=r.map(o=>`
    <li class="gallery__item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" class="img-search"/>
      </a>
      <div class="info">
        <p class="p-info-img"><b>Likes</b> ${o.likes}</p>
        <p class="p-info-img"><b>Views</b> ${o.views}</p>
        <p class="p-info-img"><b>Comments</b> ${o.comments}</p>
        <p class="p-info-img"><b>Downloads</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function I(){f.innerHTML=""}function p(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function b(){g.classList.remove("hidden")}function i(){g.classList.add("hidden")}let n="",c=1,u=0;const _=document.querySelector("#form-info"),$=document.querySelector(".load-more");_.addEventListener("submit",async r=>{if(r.preventDefault(),n=r.target.elements.searchQuery.value.trim(),!n){a.warning({message:"Please enter a search term!"});return}c=1,I(),i(),p();try{const t=await m(n,c);if(u=t.totalHits,t.hits.length===0){a.info({message:"No images found. Try another search."});return}y(t.hits),document.querySelectorAll(".gallery__item").length<u?b():(i(),a.info({message:"You've reached the end of search results."}))}catch{a.error({message:"An error occurred. Try again later."})}finally{L()}});$.addEventListener("click",async()=>{c+=1,i(),p();try{const r=await m(n,c);y(r.hits),A(),document.querySelectorAll(".gallery-item").length<u?b():(i(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Failed to load more images."})}finally{L()}});function A(){const{height:r}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
